apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lsp
resources:
  - namespace.yaml
  - configmap.template.yaml
  - secret.template.yaml
  - gate/deployment.yaml
  - gate/service.yaml
  - room/deployment.yaml
  - room/service.yaml
  - lobby/deployment.yaml
  - lobby/service.yaml
