apiVersion: v1
kind: Secret
metadata:
  name: lsp-secrets
type: Opaque
stringData:
  redis_addr: "<managed-secret:redis-addr>"
  postgres_dsn: "<managed-secret:postgres-dsn>"
  etcd_endpoints: "<managed-secret:etcd-endpoints>"
