package jingji

type mcrFanDefinition struct {
	ID     string
	Label  string
	Points int
}

func mcrFanRegistry() []mcrFanDefinition {
	return []mcrFanDefinition{
		{ID: "big_four_winds", Label: "大四喜", Points: 88},
		{ID: "big_three_dragons", Label: "大三元", Points: 88},
		{ID: "all_green", Label: "绿一色", Points: 88},
		{ID: "nine_gates", Label: "九莲宝灯", Points: 88},
		{ID: "four_kongs", Label: "四杠", Points: 88},
		{ID: "seven_shifted_pairs", Label: "连七对", Points: 88},
		{ID: "thirteen_orphans", Label: "十三幺", Points: 88},
		{ID: "all_terminals", Label: "清幺九", Points: 64},
		{ID: "little_four_winds", Label: "小四喜", Points: 64},
		{ID: "little_three_dragons", Label: "小三元", Points: 64},
		{ID: "all_honors", Label: "字一色", Points: 64},
		{ID: "four_concealed_pungs", Label: "四暗刻", Points: 64},
		{ID: "pure_terminal_chows", Label: "一色双龙会", Points: 64},
		{ID: "quadruple_chow", Label: "一色四同顺", Points: 48},
		{ID: "four_pure_shifted_pungs", Label: "一色四节高", Points: 48},
		{ID: "four_pure_shifted_chows", Label: "一色四步高", Points: 32},
		{ID: "three_kongs", Label: "三杠", Points: 32},
		{ID: "all_terminals_and_honors", Label: "混幺九", Points: 32},
		{ID: "seven_pairs", Label: "七对", Points: 24},
		{ID: "greater_honors_and_knitted_tiles", Label: "七星不靠", Points: 24},
		{ID: "all_even_pungs", Label: "全双刻", Points: 24},
		{ID: "full_flush", Label: "清一色", Points: 24},
		{ID: "pure_triple_chow", Label: "一色三同顺", Points: 24},
		{ID: "pure_shifted_pungs", Label: "一色三节高", Points: 24},
		{ID: "upper_tiles", Label: "全大", Points: 24},
		{ID: "middle_tiles", Label: "全中", Points: 24},
		{ID: "lower_tiles", Label: "全小", Points: 24},
		{ID: "pure_straight", Label: "清龙", Points: 16},
		{ID: "three_suited_terminal_chows", Label: "三色双龙会", Points: 16},
		{ID: "pure_shifted_chows", Label: "一色三步高", Points: 16},
		{ID: "all_fives", Label: "全带五", Points: 16},
		{ID: "triple_pung", Label: "三同刻", Points: 16},
		{ID: "three_concealed_pungs", Label: "三暗刻", Points: 16},
		{ID: "lesser_honors_and_knitted_tiles", Label: "全不靠", Points: 12},
		{ID: "knitted_straight", Label: "组合龙", Points: 12},
		{ID: "upper_four", Label: "大于五", Points: 12},
		{ID: "lower_four", Label: "小于五", Points: 12},
		{ID: "big_three_winds", Label: "三风刻", Points: 12},
		{ID: "mixed_straight", Label: "花龙", Points: 8},
		{ID: "reversible_tiles", Label: "推不倒", Points: 8},
		{ID: "mixed_triple_chow", Label: "三色三同顺", Points: 8},
		{ID: "mixed_shifted_pungs", Label: "三色三节高", Points: 8},
		{ID: "chicken_hand", Label: "无番和", Points: 8},
		{ID: "last_tile_draw", Label: "妙手回春", Points: 8},
		{ID: "last_tile_claim", Label: "海底捞月", Points: 8},
		{ID: "out_with_replacement_tile", Label: "杠上开花", Points: 8},
		{ID: "robbing_the_kong", Label: "抢杠和", Points: 8},
		{ID: "all_pungs", Label: "碰碰和", Points: 6},
		{ID: "half_flush", Label: "混一色", Points: 6},
		{ID: "mixed_shifted_chows", Label: "三色三步高", Points: 6},
		{ID: "all_types", Label: "五门齐", Points: 6},
		{ID: "melded_hand", Label: "全求人", Points: 6},
		{ID: "two_concealed_kongs", Label: "双暗杠", Points: 6},
		{ID: "two_dragon_pungs", Label: "双箭刻", Points: 6},
		{ID: "outside_hand", Label: "全带幺", Points: 4},
		{ID: "fully_concealed_hand", Label: "不求人", Points: 4},
		{ID: "two_melded_kongs", Label: "双明杠", Points: 4},
		{ID: "last_tile", Label: "和绝张", Points: 4},
		{ID: "dragon_pung", Label: "箭刻", Points: 2},
		{ID: "prevalent_wind", Label: "圈风刻", Points: 2},
		{ID: "seat_wind", Label: "门风刻", Points: 2},
		{ID: "concealed_hand", Label: "门前清", Points: 2},
		{ID: "all_chows", Label: "平和", Points: 2},
		{ID: "tile_hog", Label: "四归一", Points: 2},
		{ID: "double_pung", Label: "双同刻", Points: 2},
		{ID: "two_concealed_pungs", Label: "双暗刻", Points: 2},
		{ID: "concealed_kong", Label: "暗杠", Points: 2},
		{ID: "all_simples", Label: "断幺", Points: 2},
		{ID: "pure_double_chow", Label: "一般高", Points: 1},
		{ID: "mixed_double_chow", Label: "喜相逢", Points: 1},
		{ID: "short_straight", Label: "连六", Points: 1},
		{ID: "two_terminal_chows", Label: "老少副", Points: 1},
		{ID: "pung_of_terminals_or_honors", Label: "幺九刻", Points: 1},
		{ID: "melded_kong", Label: "明杠", Points: 1},
		{ID: "one_voided_suit", Label: "缺一门", Points: 1},
		{ID: "no_honors", Label: "无字", Points: 1},
		{ID: "edge_wait", Label: "边张", Points: 1},
		{ID: "closed_wait", Label: "坎张", Points: 1},
		{ID: "single_wait", Label: "单钓将", Points: 1},
		{ID: "self_drawn", Label: "自摸", Points: 1},
		{ID: "flower_tile", Label: "花牌", Points: 1},
	}
}
