apiVersion: v1
kind: Service
metadata:
  name: lsp-lobby
  labels:
    app.kubernetes.io/name: lsp-lobby
    app.kubernetes.io/part-of: lsp
spec:
  selector:
    app.kubernetes.io/name: lsp-lobby
  ports:
    - name: grpc
      port: 19081
      targetPort: grpc
    - name: obs
      port: 19084
      targetPort: obs
